### ISSUE TITLE
FEATURE REQUEST: Add Multi-Monitor Support

### ISSUE THREAD

**Issue by Barnacules** [andrebocchini/ResolutionSwitcher#1]
Could you add a -target switch where you can specify the display WMI name or identity number?

**Example(s):**
Change All Screens
ResolutionSwitcher.exe -target primary -width 1920 -height 1080

Change only extended screens (not primary)
ResolutionSwitcher.exe -target extended -width 1920 -height 1080

Change only //./Display1 using it's WMI name
ResolutionSwitcher.exe -target //./Display1 -width 1920 -height 1080

Change only display 0 using its identity number from display settings
ResolutionSwitcher.exe -target 0 -width 1920 -height 1080

Change all screens to these settings
ResolutionSwitcher.exe -target all -width 1920 -height 1080

Change screen identity 0 and 2 but leave 1 alone (middle screen)
ResolutionSwitcher.exe -target 0,2 -width 1920 -height 1080

These are all just examples of variations that would be nice to have supported for multi-monitor systems. I've been looking around and there are a lot of tools for changing different settings but none of them have all the features that the control panel does. It would be nice if one tool evolved to have it all so it could change any setting that you could do through the control panel from the command line and I hope this tool might become that.

**Comment by andrebocchini** [comment]
I had a little free time so I added something along these lines in v2.0.0. You should be able to use the WMI name:

`ResolutionSwitcher --width 1920 --height 1080 --refresh 60 --device \\.\DISPLAY2`

Give it a try. Hope it works for you.
