### ISSUE TITLE
FEATURE REQUEST: Add HDR Support

### ISSUE THREAD

**Issue by Barnacules** [andrebocchini/ResolutionSwitcher#2]
Could you add a -HDR on/off switch where you can specify that you want to enable or disable the HDR mode

Example(s):
Turn HDR mode off for the selected screen
ResolutionSwitcher.exe -hdr off -width 1920 -height 1080

Turn HDR mode on for the selected screen
ResolutionSwitcher.exe -hdr on -width 1920 -height 1080

This would be super helpful for quickly disabling and re-enabling HDR for games that you want to use it and games you don't want to use it in Windows and then simply add the command to the command line shortcut for the game so it automatically does it before the game starts. Also, would be helpful for binding to hot keys to quickly and enable and disable the feature without going into the Display control panel.

**Comment by andrebocchini** [comment]
I added some basic HDR support. Might be something along the lines of what you mentioned here.
