### ISSUE TITLE
Windows Defender Threat detected

### ISSUE THREAD

**Issue by tmulz** [andrebocchini/ResolutionSwitcher#6]
This is your official release, the latest binary you uploaded, on Sept, 5th. 

![image](https://github.com/user-attachments/assets/627e60e3-ab26-4f62-8716-b22815cfcaf7)

Uploaded to virustotal, here..
https://www.virustotal.com/gui/file/f6f5f5911b1af3c46e0fe37fc480f91fa59eb2830e4d03c4c49270b3e6c2eda6/detection

Not sure if it's a false positive or what.

Thanks!

**Comment by andrebocchini** [comment]
It's [pretty common](https://www.google.com/search?q=pyinstaller+false+positive) for that to happen (false positives) with executables created using pyinstaller. It's most likely because of the bootloaders that pyinstaller uses.
